#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


DEFAULT_PROVIDER_JSON = "~/.rcc/provider/ali-coding-plan/config.v2.json"
DEFAULT_USER_AGENT = "opencode/1.2.27"
MODEL_PREFERENCE = [
    "qwen3.6-plus",
    "qwen3-coder-plus",
    "qwen3-coder-next",
    "qwen3.5-plus",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate fin user.toml from a local RCC provider config."
    )
    parser.add_argument(
        "--provider-json",
        default=DEFAULT_PROVIDER_JSON,
        help="Source RCC provider config",
    )
    parser.add_argument("--output", required=True, help="Where to write generated user.toml")
    parser.add_argument(
        "--provider-name",
        default="ali-coding-plan",
        help="Provider alias used inside user.toml",
    )
    parser.add_argument(
        "--model",
        default=None,
        help="Override model target; defaults to preferred coding model",
    )
    parser.add_argument(
        "--scope-label",
        default="user",
        help="Comment label for generated file, e.g. user/test",
    )
    parser.add_argument(
        "--user-agent",
        default=DEFAULT_USER_AGENT,
        help="User-Agent written into user.toml",
    )
    return parser.parse_args()


def choose_model(provider: dict, requested: str | None) -> str:
    models = provider.get("models", {})
    if requested:
        if requested not in models:
            raise SystemExit(f"requested model '{requested}' not found in provider config")
        return requested

    for candidate in MODEL_PREFERENCE:
        if candidate in models:
            return candidate
    if models:
        return next(iter(models.keys()))
    raise SystemExit("provider config contains no models")


def protocol_from_type(provider_type: str) -> str:
    mapping = {
        "anthropic": "anthropic-wire",
        "openai": "open-ai-compatible",
        "openai-compatible": "open-ai-compatible",
    }
    if provider_type not in mapping:
        raise SystemExit(f"unsupported provider type '{provider_type}' for fin user.toml")
    return mapping[provider_type]


def parse_api_key_spec(raw_api_key: str) -> tuple[str, str]:
    value = raw_api_key.strip()
    if value.startswith("${") and value.endswith("}") and len(value) > 3:
        return ("env", value[2:-1])
    return ("direct", value)


def render_user_toml(
    provider_name: str,
    protocol: str,
    base_url: str,
    model: str,
    api_key_kind: str,
    api_key_value: str,
    scope_label: str,
    user_agent: str,
) -> str:
    credential_line = (
        f'api_key_env = "{api_key_value}"'
        if api_key_kind == "env"
        else f'api_key = "{api_key_value}"'
    )
    return f'''# Generated by scripts/generate-test-user-toml.py
# Source: ~/.rcc/provider/ali-coding-plan/config.v2.json
# Scope: {scope_label} provider config

default_provider = "{provider_name}"

[providers.{provider_name}]
protocol = "{protocol}"
base_url = "{base_url}"
model = "{model}"
user_agent = "{user_agent}"
{credential_line}
'''


def main() -> int:
    args = parse_args()
    provider_path = Path(args.provider_json).expanduser()
    if not provider_path.exists():
        print(f"provider config not found: {provider_path}", file=sys.stderr)
        return 1

    data = json.loads(provider_path.read_text())
    provider = data.get("provider", {})
    provider_type = provider.get("type")
    base_url = provider.get("baseURL")
    auth = provider.get("auth", {})
    api_key = auth.get("apiKey")

    if not provider_type or not base_url or not api_key:
        print(
            "provider config missing required fields: provider.type/baseURL/auth.apiKey",
            file=sys.stderr,
        )
        return 1

    model = choose_model(provider, args.model)
    protocol = protocol_from_type(provider_type)
    api_key_kind, api_key_value = parse_api_key_spec(api_key)
    output = Path(args.output).expanduser()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        render_user_toml(
            args.provider_name,
            protocol,
            base_url,
            model,
            api_key_kind,
            api_key_value,
            args.scope_label,
            args.user_agent,
        )
    )
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
